# Generated by Django 6.0.6 on 2026-06-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_data',
            field=models.FileField(default=1, upload_to='musics/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
