# Generated by Django 6.0.6 on 2026-06-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_music_favouites_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
